apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:AVvoS70kS2abfzUUOFetirIJGrPavdl5f6I7XWf3kLvbTs8wFJSlzw==,iv:l5GSmcQwXjUzgQpEACbJUlklWYd8rQZ2qzcFZUzxwb8=,tag:wyazQ0qbNWZ5xhxsOt+S4A==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TVlibWswSitpcEI0VGNx
            WmQrQk9tbS95WUMrMzNwSVlwek9TdG00cHhjClVtdnBoV2Nock1PcE9VcTJTdm56
            TzM2dW9kZWg5RmNudUFIbHVSQkVPNTAKLS0tIFRjS3V5R3JjV2w5OThLZldsYUVX
            OGV4cjVLaXZXcmFDNXl5OU9yemplRncKHhNL6sJ1oeP+/f1lQn0WCWzQ/yd8fZZU
            qNmEhDtlloXQ7dqaNZHjgsDc2g3fA8BifaO/Pd0vJtSfQLbT9ISPPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T16:25:09Z"
    mac: ENC[AES256_GCM,data:KwWvMTg97Qlau01v22LE5WnguHCUZ2Kc+cKLxxzrJlAFvBm0Qr2UBSmHRfi9ArvdaHgqOQ0AonXefQ31JL/LkrhglYBA+g5kiK7abZkA1PepZ20LVgys4DqsfwFo/Yugc5bQD53U6Ml5wxWsr2S0qMJfRjLSqXUzlri6fNYdM8U=,iv:XrtinJ6JandLGVtir8ZH4gqsmQPT4ot5yIKA21OcdXk=,tag:/CLr6l+DhlseNEFuwXbkMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
