apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: apollo
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-secret
            key: token
            namespace: external-secrets
