apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: apollo
      auth:
        serviceAccountSecretRef:
          name: onepassword-secret
          key: token
          namespace: external-secrets
