apiVersion: v1
kind: Secret
metadata:
    name: onepassword-secret
    namespace: external-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:y4SHkz3zbSL35X4C+gKdMR0S8Zo8PeDDpNDiqhrZQGYzc927rtxmBM5j9Oq30JWybfR0+4Ob6hUWyetBOSg/p61ask8rOjZeckcDAffyoZhTj0TTKbycDdBNw9FH5BTfOQTB717zruINUmKy7qU7cVYeIBjvc4sQyY3gTl4pY/yg2ocXDbkAvrLEEYBmvK1becpJBp9rUHWpg8clCWoyiB3sZIxdFnq2XZHeGiRbAxLQEt3AzunaP0DSsM6kz18YaunPbis/kGp5tcChzxcAvwxU8gSlolDGC6YSb29YAXnFAnpcHsiNTcz9oVZvLB2oE4GEC9IqSgXmbi9+sD94qwbdhv71Q1Y7Sp+0oEnMVV8kdywEJT/KZ047j3Ekkzpb2MRP8PfHhmhh6cJ6MmgmouSoO5wvRrUZIbZG7Ywuw25MNcfHd45P9bUjZtJ/GavnYDhbN8ZvtBCdUcVr4GM5bHESKDPV9dCN61cVgjfTN4lNcswCQcYDqdoWIsHKhmM/ozUpVPjO8yg2YtAbG0J4BD7iwzSFNulmPfCtAHejfoWBHJQMaC7F0Dktghyfe6yw+HwUDlVrybgWNSIeC8CInkCzflWoDWfwObNtnI7AnGPg3KsNOEeLZfAEAyOd/SfKzX8iztZxiDD0DNCaaedt8hjAjbxWFOGvpFH6gOT+VPePg1Evjg8SYQoWspSW+apGqEqiyyhU7WE2x24EqX3ePsYfv2K5QtdEaaTxUDf4aZS2+HZt3HR6UpnhB4QNV2YGhC3MwLf7SOyYMYyPJJxByDvZxX8YV3mrAPjX3RZEWQTqQ4l4PBbK/EWehxr8YDYz+9bblaDB7a0WycV5iAxR40P6nNTIpBl1jkccM4HsrLGXHF3OgDa/3cho0KVU3KKi0qDEpVLNH5rdh+hP3hyQiAck0nf3IqWaxAnDZgUSxOUqVs1PIfwlpnv7INKb76aT33+Fe9Y8CL2LCglOtLRyWa8Uqsy9UpIlsHvGsQq9ndUbv6qfYp7RHjcazNuc6V/sQlKfvMp1H0xQ/6ONb/Dbr3wufpU+7YIQ1xJIYfseCJZh2IvbdIs+c8zlLYP79qiqPFOBJAncdJiFiT8N3MDfRXDM8awKKNsQgkezKrjgVtQNUA==,iv:IOWOxlgsmAQFZdhQlnB63qn0Ptn2LPXRIjygGHtFq+Y=,tag:WHNRGPNUTM4N+o9mJqigGA==,type:str]
sops:
    age:
        - recipient: age1r7av906yds64vpcldvd33egjrxyxfhyj2jvutfsxdfw325lf8v3qe7hhgl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa2pDOEJRWjUvTTBHNEQ3
            NE14cEMxczU4TVk4Z1pPK3NFc3QxYlZ5ZDA4Ck8wRDdOdzlmbHVNWHdHL3lYVmg4
            eTh6Sm9lUDI0L1hqVldES2VXc09UTEUKLS0tIFl4Z3NtV29uYnVtS0NNSHdDUE54
            MUVvZHpINHEyVkcvbVh5WG83TTlLUzQK7C0TIiSW02P3GzD8FtFsjiqmabPtSFQz
            yOf2UCeHxGyv6Io7Y5ymejL2bOYbZjbXgm7BxYZXEoXEKb4LrtpugQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T13:02:50Z"
    mac: ENC[AES256_GCM,data:wchptojqsJZ+Awipns7fzHpCKP0W9WALBa0dBLyZRL3c1wZYzaRXdv9/BfsqjtZfb45W5ssx7tyUcM8ahq9EJoztN8nnpauH0LRflKLxBDebdA5T1RHcjWoMMGSwXp52hLZm/HjQmAkKZ4Yw4dfJvA4RGeJCL+FudTl/eWoh3AE=,iv:Y8bmwSrzxDvkspMuERhBVZr/FvCtYKf2zq0FWfq72rQ=,tag:w9xqCx1hJApk5zm22MGkOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
