resources:
  - cert-manager.yaml
  - external-dns.yaml
  - cluster-issuers.yaml
  - cnpg-operator.yaml
  - traefik.yaml
  - external-secrets.yaml
  - cluster-secret-stores.yaml
  - tofu-controller.yaml
