apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-backup-credentials
  namespace: zitadel
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: zitadel-backup-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: s3-backup-credentials/username
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: s3-backup-credentials/password
