apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: zitadel-db-pooler-rw
  namespace: zitadel
spec:
  cluster:
    name: zitadel-db
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
