apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-db
  namespace: zitadel
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi

  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
    # recovery:
    #   source: zitadel-backup-source

  externalClusters:
    - name: zitadel-backup-source
      barmanObjectStore:
        serverName: zitadel-db
        destinationPath: "s3://apollo/pg-backup/zitadel"
        endpointURL: "https://1f77cbb9b7e656d1c77bb8ac97dca2e8.r2.cloudflarestorage.com"
        s3Credentials:
          accessKeyId:
            name: zitadel-backup-credentials
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: zitadel-backup-credentials
            key: ACCESS_SECRET_KEY

  backup:
    barmanObjectStore:
      destinationPath: "s3://apollo/pg-backup/zitadel"
      endpointURL: "https://1f77cbb9b7e656d1c77bb8ac97dca2e8.r2.cloudflarestorage.com"
      s3Credentials:
        accessKeyId:
          name: zitadel-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: zitadel-backup-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 8
    retentionPolicy: "30d"
  affinity:
    podAntiAffinityType: preferred
