apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-masterkey
  namespace: zitadel
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: zitadel-masterkey
  data:
    - secretKey: masterkey
      remoteRef:
        key: zitadel-masterkey/password
