apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-smtp-secrets
  namespace: zitadel
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: zitadel-smtp-secrets
  data:
    - secretKey: host
      remoteRef:
        key: smtp-credentials/host
    - secretKey: user
      remoteRef:
        key: smtp-credentials/username
    - secretKey: password
      remoteRef:
        key: smtp-credentials/password
